language: python
python:
  - "3.6"
services:
  - docker
branches:
  only:
    - master
install:
  - cp config.py.sample config.py
  - pip install -r requirements.txt
  - docker run --name wab-redis -p 6379:6379 -d redis
script:
  - ./test.sh
