FROM metabrainz/python:3.6

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
         build-essential \
         npm \
    && rm -rf /var/lib/apt/lists/*

RUN pip3.6 install setuptools uwsgi

RUN mkdir /js
WORKDIR /js
RUN npm install && \
    npm i three

RUN mkdir -p /code/wearebeautiful.info
WORKDIR /code/wearebeautiful.info

RUN apt-get purge -y build-essential && \
    apt-get autoremove -y && \
    apt-get clean -y

COPY requirements.txt /code
RUN pip3.6 install -r /code/requirements.txt
#RUN ln -s /js /code/wearebeautiful.info/static/

ENV FLASK_APP=wearebeautiful/app.py
ENV FLAK_ENV=development
ENV FLASK_DEBUG=1
ENV FLASK_RUN_HOST=0.0.0.0

CMD /code/wearebeautiful.info/dev-server.sh

