FROM ubuntu:18.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
         build-essential \
         python3 \
         python3-dev \
         python3-pip \
         npm \
         vim \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install setuptools wheel

RUN mkdir -p /js/scss
RUN mkdir -p /gcss
WORKDIR /js
RUN npm install && \
    npm i -g sass@1.26.3 && \
    npm i bootstrap@4.4.1 jquery@3.5.0 popper.js@^1.16.0
COPY static/scss /js/scss
RUN sass --load-path=./node_modules/bootstrap/scss \
         --load-path=./ scss/custom.scss \
         /gcss/bootstrap.css

RUN mkdir -p /code/wearebeautiful.info
WORKDIR /code/wearebeautiful.info

RUN apt-get purge -y build-essential && \
    apt-get autoremove -y && \
    apt-get clean -y

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY requirements.txt /code
RUN pip3 install -r /code/requirements.txt

ENV FLASK_APP=wearebeautiful/app.py
ENV FLAK_ENV=development
ENV FLASK_DEBUG=1
ENV FLASK_RUN_HOST=0.0.0.0

CMD /code/wearebeautiful.info/dev-server.sh
